version: '2'
services:
  nodejs:
    image: node:14.7
    container_name: people-explorer-api
    command: /bin/sh -c "./run.sh"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3333:3333"
    networks:
      - people-explorer-api-network
    depends_on:
      - redis

  redis:
    container_name: people-explorer-api-redis
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"
    networks:
      - people-explorer-api-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "80:8080"
    volumes:
      - ./swagger.json:/swagger.json
    environment:
      SWAGGER_JSON: /swagger.json
      #API_URL: "http://localhost:3333"

networks:
  people-explorer-api-network:
    driver: bridge
